server:
  error:
    path: '/error'
  servlet:
    context-path: '/api'

spring:
  application:
    name: 'employee-api'

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/ukeess_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username:
    password:

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

# ===============================
# = METRICS
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    com.ukeess: debug
#    org.hibernate: debug

# ===============================
# = MOCK DETAILS
# ===============================
token:
  secret_key: 'my-token-secret'