spring:
  application:
    name: employee-api

  datasource:
#    url: jdbc:mysql://localhost:3306/ukeess_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/ukeess_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
    level:
      com.ukeess: debug