server:
  error:
    path: /error
  servlet:
    context-path: /api

spring:
  application:
    name: employee-api

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/ukeess_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    com.ukeess: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
