server:
  error:
    path: '/error'
  servlet:
    context-path: '/api'

spring:
  application:
    name: 'employee-api'

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/ukeess_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: ALWAYS


  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = METRICS
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    com.ukeess: debug
#    org.hibernate: debug

# ===============================
# = MOCK DETAILS
# ===============================
token:
  secret_key_mock: 'my-token-secret'
  username_mock: 'harry'
  password_mock: 'potter'