server:
  error:
    path: /error
  servlet:
    context-path: /api

spring:
  application:
    name: employee-api

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/ukeess_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: always

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    com.ukeess: debug
#    org.hibernate: debug